name: "RPL-2023-CICD Demo"
on:
  push:
    branches:
    - main
jobs:
  code-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Do python linter test check
        run: |
          python -m ensurepip --upgrade
          python -m pip install pylint
          pylint app.py
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create folder for copying file
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: mkdir -p /home/rplcicd/13512043 
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "app.py"
        target: "/home/rplcicd/13512043/"
    - name: kill existing flask app
      continue-on-error: true
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: pkill -f 12043
    - name: start flask app
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /home/rplcicd/13512043 && python3 -m flask run --host=0.0.0.0 --port=12043 & 
